"""Remove profile_pic from User

Revision ID: 743048e7f40a
Revises: 36ad32a06da6
Create Date: 2025-07-18 11:04:11.584371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '743048e7f40a'
down_revision = '36ad32a06da6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('profile_pic')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_pic', sa.VARCHAR(length=300), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
